"""
Offline runner for computationally heavy Fair CVAE experiments.
This script executes real code from `more strict .py` and stores summary outputs
for the Results page.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OFFLINE_DIR = ROOT / "webapp" / "offline_results"
OFFLINE_DIR.mkdir(parents=True, exist_ok=True)


def load_more_strict_module():
    module_path = ROOT / "more strict .py"
    spec = importlib.util.spec_from_file_location("more_strict_module", module_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load module from: {module_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def main(csv_path: str = "tech_diversity_hiring_data.csv"):
    module = load_more_strict_module()
    result = module.run_experiment(csv_path)

    method_rows = []

    baseline = result["baseline"]
    method_rows.append(
        {
            "method": "Baseline MLP (more strict .py)",
            "accuracy": round(float(baseline["accuracy"]), 4),
            "f1": round(float(baseline["f1"]), 4),
            "min_di": round(float(baseline["fairness"]["DI"].min()), 4),
            "source": "Generated by more strict .py",
            "availability": "available",
        }
    )

    for mode in ["adv_only", "no_adv", "full"]:
        cal = result["calibrated"].get(mode)
        if cal is None:
            continue
        method_rows.append(
            {
                "method": f"Fair CVAE {mode} (more strict .py)",
                "accuracy": round(float(cal["accuracy"]), 4),
                "f1": round(float(cal["f1"]), 4),
                "min_di": round(float(cal["fairness"]["DI"].min()), 4),
                "source": "Generated by more strict .py",
                "availability": "available",
            }
        )

    payload = {
        "method_comparison": method_rows,
        "latent_metrics": [],
        "note": "Fair CVAE method metrics generated offline from more strict .py. Latent charts come from latent_vis/*.png.",
    }

    out_file = OFFLINE_DIR / "fair_cvae_results.json"
    out_file.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"Saved offline summary: {out_file}")


if __name__ == "__main__":
    main()
